require "open-uri"

# clubs = [
#   {
#     name: "Club",
#     description: "This is club. You join.",
#     public: true,
#     owner_id: 3,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711214986/club%20pictures/formal-studio-portrait-of-six-serious-young-adults_qrrlhp.jpg",
#   },
#   {
#     name: "Readers' guild",
#     description: "Join us every week for a book, a beverage and some cubed cheese!.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711214993/club%20pictures/104702698-GettyImages-583816330-book-club_zyl10e.jpg",
#   },
#   {
#     name: "Human gathering",
#     description: "We are human organisms seeking to share oxygen and edible snacks around a hobby.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215010/club%20pictures/deathofcaesar.0.0_al1ved.jpg",
#   },
#   {
#     name: "Carl",
#     description: "Carl",
#     public: true,
#     owner_id: 3,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215017/club%20pictures/Carl-design-sketch-name_xiue8s.png",
#   },
#   {
#     name: "On company time",
#     description: "Dungeons & Dragons & Cheese",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215024/club%20pictures/21DUNGEONS-DRAGONS1-videoSixteenByNineJumbo1600-v2_qjudpt.jpg",
#   },
#   {
#     name: "Robot gathering",
#     description: "Looking to share oil around the office electric socket.",
#     public: true,
#     owner_id: 2,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215038/club%20pictures/326b4f32-8d7c-416c-bf79-5d1072da45f1_screenshot_ryv0kl.jpg",
#   },
#   {
#     name: "Alien gathering",
#     description: "Please don't ask us to probe you.",
#     public: true,
#     owner_id: 3,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215031/club%20pictures/326b4f32-8d7c-416c-bf79-5d1072da45f1_screenshot_rja08e.jpg",
#   },

#   {
#     name: "Chess master",
#     description: "Fischer ? I barely know her.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215044/club%20pictures/1200px-San_Francisco_Mechanics_E2_80_99_Institute-0700_cxxrl4.jpg",
#   },

#   {
#     name: "Teaching our rats how to cook",
#     description: "We have rats. They cook. This isn't entirely legal. I mean it is. This is legal.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215052/club%20pictures/linguiniratatouille_vswanc.jpg",
#   },

#   {
#     name: "The Craft Zone",
#     description: "The rule is to always use too much glitter.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215056/club%20pictures/LEARNING11_ijhidn.webp",
#   },
#   {
#     name: "Survivalist Bootcamp",
#     description: "This will self-destruct in 4 to 5 business days",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215061/club%20pictures/high_pztshx.jpg",
#   },

#   {
#     name: "Use your words",
#     description: "Let's start a writing workshop! Prompts and feedback galore.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711216317/club%20pictures/AccComm-3293117576_05f43d8305_z_r2vvan.webp",
#   },
#   {
#     name: "This is not a trap",
#     description: "How do you feel about damp constricted places ?",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711216398/club%20pictures/5d35saupmwu5k066met8d6mko9ii_sp7seg.jpg",
#   },
#   {
#     name: "Lawyer Support Group",
#     description: "Lawyer? I barely know her. I know her. She's paying me.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215085/club%20pictures/cover7_g4hvxn.jpg",
#   },
#   {
#     name: "Collective screaming",
#     description: "Channeling all your emotions into noise pollution",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215090/club%20pictures/1_hOqxrAl2ctCefDvuqD7QJA_addv4p.jpg",
#   },
#   {
#     name: "Yoga & Yogurt",
#     description: "Unravel your knots and grab a spoon with us!",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215099/club%20pictures/InspireYogaGV-032019_PRT-25-scaled_bieght.jpg",
#   },
#   {
#     name: "Come in. Commune!",
#     description: "Do you feel truly held by the people around you ?",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215105/club%20pictures/l-intro-1644447165_btied4.jpg",
#   },
#   {
#     name: "Yes, and ? ",
#     description: "Nothing but improv!",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215113/club%20pictures/5616_savnel.jpg",
#   },
#   {
#     name: "Muppet Goulag",
#     description: "You join. Straight to Muppet Goulag.",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215118/club%20pictures/gulag_txemb5.jpg",
#   },
#   {
#     name: "Blood, guts and popcorn",
#     description: "I know what you're going to do this summer! Watch horror movie marathons as a group",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215129/club%20pictures/1440_scary_movie_feat-1440x700_hmihim.jpg",
#   },
#   {
#     name: "Group tape watching",
#     description: "We got this very normal tape that we would like to watch together",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215134/club%20pictures/the-ring-video-samara-video-vhs_eltm2f.jpg",
#   },

#   {
#     name: "The Card Collective",
#     description: "Aiming to unite a jovial group of card game fanatics.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215140/club%20pictures/Group_Card_Game_uy0dhx.jpg",
#   },
#   {
#     name: "Sabacc",
#     description: "The fairest game of chance on this side of the galaxy.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1711215146/club%20pictures/lando-twins-sabacc-solo-a-star-wars-story_efak7i.jpg",
#   },
#   {
#     name: "Cannibals (Not So) Anonymous",
#     description: "Free snacks provided. Paul might be there",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172214/club%20pictures/CLUB_ID_32_-_cannibals_anonymous_kdqpgv.jpg",
#   },
#   {
#     name: "Divorcee ? Digiorno",
#     description: "Providing you with a support system and pizza so you don't key your ex husband's car.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172214/club%20pictures/CLUB_ID_33_-_Divorcee___Digiorno_muf8iw.jpg",
#   },
#   {
#     name: "Slasher roleplay",
#     description: "Our killer got mononucleosis at a festival.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172203/club%20pictures/CLUB_ID_34_-_Slasher_RP_okkxs6.jpg",
#   },
#   {
#     name: "Making an app that allows you to join clubs",
#     description: "Nothing to do with this one. This is an original and separate idea.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172204/club%20pictures/CLUB_ID_35_-_Making_app_3gather_vit0jd.jpg",
#   }, {
#     name: "Skewer? I hardly know her",
#     description: "Have a barbecue with us ! Bring your own parts.",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172213/club%20pictures/CLUB_ID_29_-_SKEWER_HARDLY_KNOW_HER_doseaj.jpg",
#   },
#   {
#     name: "Drugs. I mean not drugs.",
#     description: "We do not sell drugs. They are bad, yo!",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172205/club%20pictures/CLUB_ID_8_-_Not_drugs_r47l08.jpg",
#   },
#   {
#     name: "Hang out with Paul",
#     description: "I'm Paul. Please guys. Anyone.",
#     public: true,
#     owner_id: 1,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172206/club%20pictures/CLUB_ID_10_-_Paul_smijgn.webp",
#   },
#   {
#     name: "Don't hang out with Paul",
#     description: "Do not trust him. He WILL steal both your pet AND your underwear. Also lamps. And condiments.",
#     public: true,
#     owner_id: 5,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172208/club%20pictures/CLUB_ID_11_-_Fuck_Paul_rhqafk.jpg",
#   },
#   {
#     name: "Chicken on a sofa",
#     description: "Pranks! Chicken! Breaking and entering strangers' homes!",
#     public: true,
#     owner_id: 3,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172209/club%20pictures/CLUB_ID_13_-_Chicken_on_a_sofa_l86aoo.jpg",
#   },
#   {
#     name: "The Teds",
#     description: "Collecting Teds",
#     public: true,
#     owner_id: 4,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172210/club%20pictures/CLUB_ID_14_-_The_Teds_dxeffe.jpg",
#   },
#   {
#     name: "Throwing rocks at people in general ",
#     description: "You have to bring your own rock. The people are free range.",
#     public: true,
#     owner_id: 3,
#     category_id: (1..32).to_a.sample,
#     image_url: "https://res.cloudinary.com/dgpk6t1we/image/upload/v1708172211/club%20pictures/CLUB_ID_18_-_Throwing_rocks_at_people_zeby2e.jpg",
#   },

# ]
clubs = [
  {
    name: "Club",
    description: "This is club. You join.",
    public: true,
    owner_id: 3,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/club.jpg",
  },
  {
    name: "Readers' guild",
    description: "Join us every week for a book, a beverage and some cubed cheese!.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/readers.jpg",
  },
  {
    name: "Human gathering",
    description: "We are human organisms seeking to share oxygen and edible snacks around a hobby.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/humans.jpg",
  },
  {
    name: "Carl",
    description: "Carl",
    public: true,
    owner_id: 3,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/carl.png",
  },
  {
    name: "On company time",
    description: "Dungeons & Dragons & Cheese",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/dnd.jpg",
  },
  {
    name: "Robot gathering",
    description: "Looking to share oil around the office electric socket.",
    public: true,
    owner_id: 2,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/robot.jpg",
  },
  {
    name: "Alien gathering",
    description: "Please don't ask us to probe you.",
    public: true,
    owner_id: 3,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/alien.jpg",
  },

  {
    name: "Chess master",
    description: "Fischer ? I barely know her.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/chess.jpg",
  },

  {
    name: "Teaching our rats how to cook",
    description: "We have rats. They cook. This isn't entirely legal. I mean it is. This is legal.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/rat.jpg",
  },

  {
    name: "The Craft Zone",
    description: "The rule is to always use too much glitter.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/crafts.webp",
  },
  {
    name: "Survivalist Bootcamp",
    description: "This will self-destruct in 4 to 5 business days",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/survivalist.jpg",
  },

  {
    name: "Use your words",
    description: "Let's start a writing workshop! Prompts and feedback galore.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/words.webp",
  },
  {
    name: "This is not a trap",
    description: "How do you feel about damp constricted places ?",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/trap.jpg",
  },
  {
    name: "Lawyer Support Group",
    description: "Lawyer? I barely know her. I know her. She's paying me.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/lawyers.jpg",
  },
  {
    name: "Collective screaming",
    description: "Channeling all your emotions into noise pollution",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/screaming.jpg",
  },
  {
    name: "Yoga & Yogurt",
    description: "Unravel your knots and grab a spoon with us!",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/yoga.jpg",
  },
  {
    name: "Come in. Commune!",
    description: "Do you feel truly held by the people around you ?",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/come_in.jpg",
  },
  {
    name: "Yes, and ? ",
    description: "Nothing but improv!",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/yes_and.jpg",
  },
  {
    name: "Muppet Goulag",
    description: "You join. Straight to Muppet Goulag.",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/gulag.jpg",
  },
  {
    name: "Blood, guts and popcorn",
    description: "I know what you're going to do this summer! Watch horror movie marathons as a group",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/blood_popcorn.jpg",
  },
  {
    name: "Group tape watching",
    description: "We got this very normal tape that we would like to watch together",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/tape_watching.jpg",
  },

  {
    name: "The Card Collective",
    description: "Aiming to unite a jovial group of card game fanatics.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/cards.jpg",
  },
  {
    name: "Sabacc",
    description: "The fairest game of chance on this side of the galaxy.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/sabacc.jpg",
  },
  {
    name: "Cannibals (Not So) Anonymous",
    description: "Free snacks provided. Paul might be there",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/cannibals.jpg",
  },
  {
    name: "Divorcee ? Digiorno",
    description: "Providing you with a support system and pizza so you don't key your ex husband's car.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/divorcee.jpg",
  },
  {
    name: "Slasher roleplay",
    description: "Our killer got mononucleosis at a festival.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/slasher.jpg",
  },
  {
    name: "Making an app that allows you to join clubs",
    description: "Nothing to do with this one. This is an original and separate idea.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/3gather.jpg",
  }, {
    name: "Skewer? I hardly know her",
    description: "Have a barbecue with us ! Bring your own parts.",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/SKEWER.jpg",
  },
  {
    name: "Drugs. I mean not drugs.",
    description: "We do not sell drugs. They are bad, yo!",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/Not_drugs.jpg",
  },
  {
    name: "Hang out with Paul",
    description: "I'm Paul. Please guys. Anyone.",
    public: true,
    owner_id: 1,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/Paul.webp",
  },
  {
    name: "Don't hang out with Paul",
    description: "Do not trust him. He WILL steal both your pet AND your underwear. Also lamps. And condiments.",
    public: true,
    owner_id: 5,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/Fuck_Paul.jpg",
  },
  {
    name: "Chicken on a sofa",
    description: "Pranks! Chicken! Breaking and entering strangers' homes!",
    public: true,
    owner_id: 3,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/chicken.jpg",
  },
  {
    name: "The Teds",
    description: "Collecting Teds",
    public: true,
    owner_id: 4,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/Teds.jpg",
  },
  {
    name: "Throwing rocks at people in general ",
    description: "You have to bring your own rock. The people are free range.",
    public: true,
    owner_id: 3,
    category_id: (1..32).to_a.sample,
    image_url: "public/club pictures/rocks.jpg",
  },

]
clubs.each do |club|
  if club[:image_url].include?("http")
    Club.create!(club.except(:image_url)).image.attach(io: URI.open(club[:image_url]), filename: "#{club[:name]}")
    puts "Created club: " + club[:name]
  else
    Club.create!(club.except(:image_url)).image.attach(io: File.open(club[:image_url]), filename: "#{club[:name]}.jpg")
    puts "Created club: " + club[:name]
  end
end

# folder = "development/test"

# clubs.each do |club|
#   upload = Cloudinary::Uploader.upload(club[:image_url], folder: folder)
#   puts "uploaded image #{upload}"
# end

# clubs.each do |club|
#   Club.create!
# end
