posts = [
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 1 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 2 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 3 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 4 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 6 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 7 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 8 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 9 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 10 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 11 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 12 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 13 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 14 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 15 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 16 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 17 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 18 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 19 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 20 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 21 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 23 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 24 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 25 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 26 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 27 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 28 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 29 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 30 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 31 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 32 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 33 },
  { content: "AAAAAAAAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 34 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "AAAAAAAAAAAAAAAAAAAAH", user_id: 1, club_id: 22 },
  { content: "I have joined", user_id: 1, club_id: 1 },
  { content: "Okay now what ?", user_id: 1, club_id: 1 },
  { content: "The oxygen outside today was a little spicy am i right ? ah ah. Can't wait for the next event!", user_id: 3, club_id: 3 },
  { content: "Oh my deity, these taxes! When will the big man stop picking on the little boy!", user_id: 3, club_id: 3 },
  { content: "Is nobody going to talk about the obvious alien who joined ?", user_id: 3, club_id: 2 },
  { content: "Carl", user_id: 8, club_id: 4 },
  { content: "Carl ?", user_id: 8, club_id: 4 },
  { content: "Carl", user_id: 8, club_id: 4 },
  { content: "Carl", user_id: 8, club_id: 4 },
  { content: "Carl ???", user_id: 8, club_id: 4 },
  { content: "Carl !!!!!!!", user_id: 8, club_id: 4 },
  { content: "Carl", user_id: 8, club_id: 4 },
  { content: "It smells weird in here", user_id: 1, club_id: 4 },
  { content: "Hey guys. I am also human. I enjoy regular everyday things like photosynthesis and throwing ball.", user_id: 3, club_id: 3 },
  { content: "Could we change the schedule please ? I've been impaled.", user_id: 1, club_id: 2 },
  { content: "I'm bringing chicken feet on thursday.", user_id: 3, club_id: 2 },
  { content: "Stop asking me to change the schedule. If you can't come at 3 AM on a wednesday, that sounds like a you problem.", user_id: 2, club_id: 2 },
  { content: "Can't come. Wife gave birth to a mouse. He's surprisingly verbal.", user_id: 3, club_id: 2 },
  { content: "Hello! Does anybody know how to get illegal substances., The more illegal, the better", user_id: 5, club_id: 1 },
  { content: "I'm sorry, it's over. I can't do this anymore.", user_id: 3, club_id: 2 },
  { content: "I, for one, don't think anybody here is an alien. And even if there were, that'd be cool or whatever.", user_id: 3, club_id: 2 },
  { content: "I'm so happy to be here guys. I can be trusted with weapons.", user_id: 5, club_id: 1 },
  { content: "Hello! Does anybody know how to get illegal substances., The more illegal, the better", user_id: 5, club_id: 1 },
  { content: "I am so hungry", user_id: 1, club_id: 2 },
  { content: "Heloooooooooo", user_id: 1, club_id: 32 },
]

posts.each do |post|
  Post.create!(post)
  puts "Created post for user: #{post[:user_id]} in club: #{post[:club_id]}"
end
